name: etoolz
version: 1.0.0
apiVersion: 1.16.5
main: com.eiztripsdev.Main
commands:
  wspeed:
    description: Устанавливает скорость ходьбы.

  fspeed:
    description: Устанавливает скорость полёта.

  fly:
    description: Включает/выключает полет игрока.

  vanish:
    description: Выключает/Включает видимость игрока.
  v:
    description: Выключает/Включает видимость игрока.

  broadcast:
    description: Отправляет сообщение всем игрокам.
  bc:
    description: Отправляет сообщение всем игрокам.

  heal:
    description: Вылечить здоровье игроку
    
  god:
    description: Включает/выключает бессмертие игрока

  gamemode:
    description: Изменяет режим игры игроку
  gm:
    description: Изменяет режим игры игроку

  kick:
    description: Кикнуть игрока

  ban:
    description: Забанить игрока
  
  unban:
    description: Разбанить игрока
  
  inventory:
    description: Открыть инвентарь игрока

  inv:
    description: Открыть инвентарь игрока
  
  echest:
    description: Открыть эндер-сундук игрока

  enderchest:
    description: Открыть эндер-сундук игрока
  
  mute:
   description: Замутить игрока

  unmute:
    description: Размутить игрока